### ISSUE TITLE
Custom Play Until Done fires at an inconsistent time on Chrome player

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-play-until-done#10]
*What should happen*
When triggering PUD using a custom element it should fire at a consistent time.

*What currently happens*
When PUD is called at the end of an animation the start of the next animation "loop" is visible when running in Chrome OS. This is not seen in Windows.

*Steps to recreate*
- Add the Famous Scientists Facts Template to a schedule and select PUD: https://apps.risevision.com/templates/edit/9bcf28b6-78b1-4e90-ae13-d0315014bbbd/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f
- When the animation completes after the 3rd scientist the 1st scientist will show briefly before the schedule moves on
- The code is set up to restart the animation in case a user wants to set a duration, but this call to restart is made after the call to PUD

It may be that there is an option to delay the call to restart the animation however it would be good to know if there is a set PUD delay and why the same behaviour is not being seen in Windows. Thanks!

**Comment by andrecardoso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) PUD issues #9 and #10](https://trello.com/c/yJAI96YD/280-2-pud-issues-9-and-10)
