### ISSUE TITLE
Custom PUD elements are surfaced in the editor

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-play-until-done#5]
**What should happen**

When a custom PUD element is added using `<rise-play-until-done>` they should be hidden from view in the attribute editor

**What currently happens**

When a custom PUD element is added it is visible in the attribute editor. Clicking on 'edit' takes you to a blank screen. Issue is visible here: https://apps.risevision.com/templates/edit/425c5648-2a4c-4fd4-bf7f-a4c405da227c/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

**Comment by andrecardoso** [comment]
@pcsandford this has been fixed by https://github.com/Rise-Vision/html-template-library/pull/320 

New templates that use `rise-play-until-done` will get the fix. New build is required for templates already published that use it.
