### ISSUE TITLE
When PUD is enabled Template will freeze on Chrome OS

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/rise-play-until-done#9]
### What is the expected behavior?
If a Template is added to a schedule with PUD enabled it should play for the duration that is defined by that template and move onto the next Template.

### What is the actual behavior?
The template will play for a period of time then periodically fail to load any data or fire the done command and does not move onto the next Template. This only happens with chrome os.

### What steps can be taken to replicate the problem?
Add several of the Famous Facts Templates to a schedule and enable PUD. https://www.screencast.com/t/GQa0uhuGuu Watch for a period of an hour or two eventually the schedule will stop on one particular template and freeze and never move to the next template. If you define a set duration for each tempalte it never freezes which is why we think this has to do with the Templates interaction with PUD.  
https://github.com/Rise-Vision/html-template-library/tree/master/auto-update-famous-artists
https://github.com/Rise-Vision/html-template-library/tree/master/auto-update-famous-entrepreneurs
https://github.com/Rise-Vision/html-template-library/tree/master/auto-update-famous-scientists
https://github.com/Rise-Vision/html-template-library/tree/master/auto-update-famous-women

**Comment by mmeiers** [comment]
@andrecardoso I can replicate this on my chrome os machine so it's not limited to uptime wall fyi. Let me know if you cant and Ill see if I can send some pictures of dev console.

**Comment by andrecardoso** [comment]
@mmeiers was this fixed with @pcsandford latest changes in the templates?

**Comment by mmeiers** [comment]
@andrecardoso no it was not. He is going to try one more thing.

**Comment by andrecardoso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) PUD issues #9 and #10](https://trello.com/c/yJAI96YD/280-2-pud-issues-9-and-10)

**Comment by andrecardoso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) PUD issues #9 and #10](https://trello.com/c/yJAI96YD/280-2-pud-issues-9-and-10)
